-- Candidate 023: 33 ERP module tables derived from Erp*DO and Mapper contracts.
-- All columns are scoped by tenant_id. DECIMAL(24,6) keeps fractional quantities and prices.
-- Additive only, no DROP/IF NOT EXISTS; MySQL DDL batches are non-atomic.
-- Validate independent databases, inventory/receipt flows and tenant checks BEFORE deployment.

CREATE TABLE `erp_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `no` VARCHAR(100) DEFAULT NULL,
  `remark` TEXT,
  `status` TINYINT DEFAULT NULL,
  `sort` INT DEFAULT NULL,
  `default_status` BIT(1) DEFAULT b'0',
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_account_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_account_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_account';

CREATE TABLE `erp_finance_payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `payment_time` DATETIME DEFAULT NULL,
  `finance_user_id` BIGINT DEFAULT NULL,
  `supplier_id` BIGINT DEFAULT NULL,
  `account_id` BIGINT DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `discount_price` DECIMAL(24,6) DEFAULT NULL,
  `payment_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_finance_payment_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_finance_payment_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_finance_payment';

CREATE TABLE `erp_finance_payment_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `payment_id` BIGINT DEFAULT NULL,
  `biz_type` INT DEFAULT NULL,
  `biz_id` BIGINT DEFAULT NULL,
  `biz_no` VARCHAR(255) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `paid_price` DECIMAL(24,6) DEFAULT NULL,
  `payment_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_finance_payment_item_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_finance_payment_item_parent` (`tenant_id`, `payment_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_finance_payment_item';

CREATE TABLE `erp_finance_receipt` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `receipt_time` DATETIME DEFAULT NULL,
  `finance_user_id` BIGINT DEFAULT NULL,
  `customer_id` BIGINT DEFAULT NULL,
  `account_id` BIGINT DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `discount_price` DECIMAL(24,6) DEFAULT NULL,
  `receipt_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_finance_receipt_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_finance_receipt_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_finance_receipt';

CREATE TABLE `erp_finance_receipt_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `receipt_id` BIGINT DEFAULT NULL,
  `biz_type` INT DEFAULT NULL,
  `biz_id` BIGINT DEFAULT NULL,
  `biz_no` VARCHAR(255) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `receipted_price` DECIMAL(24,6) DEFAULT NULL,
  `receipt_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_finance_receipt_item_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_finance_receipt_item_parent` (`tenant_id`, `receipt_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_finance_receipt_item';

CREATE TABLE `erp_product_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `code` VARCHAR(255) DEFAULT NULL,
  `sort` INT DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_product_category_tenant` (`tenant_id`, `deleted`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_product_category';

CREATE TABLE `erp_product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `bar_code` VARCHAR(255) DEFAULT NULL,
  `category_id` BIGINT DEFAULT NULL,
  `unit_id` BIGINT DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `standard` VARCHAR(255) DEFAULT NULL,
  `remark` TEXT,
  `expiry_day` INT DEFAULT NULL,
  `weight` DECIMAL(24,6) DEFAULT NULL,
  `purchase_price` DECIMAL(24,6) DEFAULT NULL,
  `sale_price` DECIMAL(24,6) DEFAULT NULL,
  `min_price` DECIMAL(24,6) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_product_tenant` (`tenant_id`, `deleted`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_product';

CREATE TABLE `erp_product_unit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_product_unit_tenant` (`tenant_id`, `deleted`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_product_unit';

CREATE TABLE `erp_purchase_in` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `supplier_id` BIGINT DEFAULT NULL,
  `account_id` BIGINT DEFAULT NULL,
  `in_time` DATETIME DEFAULT NULL,
  `order_id` BIGINT DEFAULT NULL,
  `order_no` VARCHAR(255) DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `payment_price` DECIMAL(24,6) DEFAULT NULL,
  `total_product_price` DECIMAL(24,6) DEFAULT NULL,
  `total_tax_price` DECIMAL(24,6) DEFAULT NULL,
  `discount_percent` DECIMAL(24,6) DEFAULT NULL,
  `discount_price` DECIMAL(24,6) DEFAULT NULL,
  `other_price` DECIMAL(24,6) DEFAULT NULL,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_in_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_purchase_in_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_purchase_in';

CREATE TABLE `erp_purchase_in_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `in_id` BIGINT DEFAULT NULL,
  `order_item_id` BIGINT DEFAULT NULL,
  `warehouse_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `tax_percent` DECIMAL(24,6) DEFAULT NULL,
  `tax_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_in_items_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_purchase_in_items_parent` (`tenant_id`, `in_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_purchase_in_items';

CREATE TABLE `erp_purchase_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `supplier_id` BIGINT DEFAULT NULL,
  `account_id` BIGINT DEFAULT NULL,
  `order_time` DATETIME DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `total_product_price` DECIMAL(24,6) DEFAULT NULL,
  `total_tax_price` DECIMAL(24,6) DEFAULT NULL,
  `discount_percent` DECIMAL(24,6) DEFAULT NULL,
  `discount_price` DECIMAL(24,6) DEFAULT NULL,
  `deposit_price` DECIMAL(24,6) DEFAULT NULL,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `remark` TEXT,
  `in_count` DECIMAL(24,6) DEFAULT NULL,
  `return_count` DECIMAL(24,6) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_order_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_purchase_order_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_purchase_order';

CREATE TABLE `erp_purchase_order_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `tax_percent` DECIMAL(24,6) DEFAULT NULL,
  `tax_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `in_count` DECIMAL(24,6) DEFAULT NULL,
  `return_count` DECIMAL(24,6) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_order_items_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_purchase_order_items_parent` (`tenant_id`, `order_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_purchase_order_items';

CREATE TABLE `erp_purchase_return` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `supplier_id` BIGINT DEFAULT NULL,
  `account_id` BIGINT DEFAULT NULL,
  `return_time` DATETIME DEFAULT NULL,
  `order_id` BIGINT DEFAULT NULL,
  `order_no` VARCHAR(255) DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `refund_price` DECIMAL(24,6) DEFAULT NULL,
  `total_product_price` DECIMAL(24,6) DEFAULT NULL,
  `total_tax_price` DECIMAL(24,6) DEFAULT NULL,
  `discount_percent` DECIMAL(24,6) DEFAULT NULL,
  `discount_price` DECIMAL(24,6) DEFAULT NULL,
  `other_price` DECIMAL(24,6) DEFAULT NULL,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_return_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_purchase_return_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_purchase_return';

CREATE TABLE `erp_purchase_return_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `return_id` BIGINT DEFAULT NULL,
  `order_item_id` BIGINT DEFAULT NULL,
  `warehouse_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `tax_percent` DECIMAL(24,6) DEFAULT NULL,
  `tax_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_return_items_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_purchase_return_items_parent` (`tenant_id`, `return_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_purchase_return_items';

CREATE TABLE `erp_supplier` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `contact` VARCHAR(255) DEFAULT NULL,
  `mobile` VARCHAR(32) DEFAULT NULL,
  `telephone` VARCHAR(32) DEFAULT NULL,
  `email` VARCHAR(254) DEFAULT NULL,
  `fax` VARCHAR(32) DEFAULT NULL,
  `remark` TEXT,
  `status` TINYINT DEFAULT NULL,
  `sort` INT DEFAULT NULL,
  `tax_no` VARCHAR(255) DEFAULT NULL,
  `tax_percent` DECIMAL(24,6) DEFAULT NULL,
  `bank_name` VARCHAR(255) DEFAULT NULL,
  `bank_account` VARCHAR(255) DEFAULT NULL,
  `bank_address` VARCHAR(500) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_supplier_tenant` (`tenant_id`, `deleted`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_supplier';

CREATE TABLE `erp_customer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `contact` VARCHAR(255) DEFAULT NULL,
  `mobile` VARCHAR(32) DEFAULT NULL,
  `telephone` VARCHAR(32) DEFAULT NULL,
  `email` VARCHAR(254) DEFAULT NULL,
  `fax` VARCHAR(32) DEFAULT NULL,
  `remark` TEXT,
  `status` TINYINT DEFAULT NULL,
  `sort` INT DEFAULT NULL,
  `tax_no` VARCHAR(255) DEFAULT NULL,
  `tax_percent` DECIMAL(24,6) DEFAULT NULL,
  `bank_name` VARCHAR(255) DEFAULT NULL,
  `bank_account` VARCHAR(255) DEFAULT NULL,
  `bank_address` VARCHAR(500) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_customer_tenant` (`tenant_id`, `deleted`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_customer';

CREATE TABLE `erp_sale_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `customer_id` BIGINT DEFAULT NULL,
  `account_id` BIGINT DEFAULT NULL,
  `sale_user_id` BIGINT DEFAULT NULL,
  `order_time` DATETIME DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `total_product_price` DECIMAL(24,6) DEFAULT NULL,
  `total_tax_price` DECIMAL(24,6) DEFAULT NULL,
  `discount_percent` DECIMAL(24,6) DEFAULT NULL,
  `discount_price` DECIMAL(24,6) DEFAULT NULL,
  `deposit_price` DECIMAL(24,6) DEFAULT NULL,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `remark` TEXT,
  `out_count` DECIMAL(24,6) DEFAULT NULL,
  `return_count` DECIMAL(24,6) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_order_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_sale_order_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_sale_order';

CREATE TABLE `erp_sale_order_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `tax_percent` DECIMAL(24,6) DEFAULT NULL,
  `tax_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `out_count` DECIMAL(24,6) DEFAULT NULL,
  `return_count` DECIMAL(24,6) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_order_items_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_sale_order_items_parent` (`tenant_id`, `order_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_sale_order_items';

CREATE TABLE `erp_sale_out` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `customer_id` BIGINT DEFAULT NULL,
  `account_id` BIGINT DEFAULT NULL,
  `sale_user_id` BIGINT DEFAULT NULL,
  `out_time` DATETIME DEFAULT NULL,
  `order_id` BIGINT DEFAULT NULL,
  `order_no` VARCHAR(255) DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `receipt_price` DECIMAL(24,6) DEFAULT NULL,
  `total_product_price` DECIMAL(24,6) DEFAULT NULL,
  `total_tax_price` DECIMAL(24,6) DEFAULT NULL,
  `discount_percent` DECIMAL(24,6) DEFAULT NULL,
  `discount_price` DECIMAL(24,6) DEFAULT NULL,
  `other_price` DECIMAL(24,6) DEFAULT NULL,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_out_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_sale_out_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_sale_out';

CREATE TABLE `erp_sale_out_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `out_id` BIGINT DEFAULT NULL,
  `order_item_id` BIGINT DEFAULT NULL,
  `warehouse_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `tax_percent` DECIMAL(24,6) DEFAULT NULL,
  `tax_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_out_items_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_sale_out_items_parent` (`tenant_id`, `out_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_sale_out_items';

CREATE TABLE `erp_sale_return` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `customer_id` BIGINT DEFAULT NULL,
  `account_id` BIGINT DEFAULT NULL,
  `sale_user_id` BIGINT DEFAULT NULL,
  `return_time` DATETIME DEFAULT NULL,
  `order_id` BIGINT DEFAULT NULL,
  `order_no` VARCHAR(255) DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `refund_price` DECIMAL(24,6) DEFAULT NULL,
  `total_product_price` DECIMAL(24,6) DEFAULT NULL,
  `total_tax_price` DECIMAL(24,6) DEFAULT NULL,
  `discount_percent` DECIMAL(24,6) DEFAULT NULL,
  `discount_price` DECIMAL(24,6) DEFAULT NULL,
  `other_price` DECIMAL(24,6) DEFAULT NULL,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_return_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_sale_return_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_sale_return';

CREATE TABLE `erp_sale_return_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `return_id` BIGINT DEFAULT NULL,
  `order_item_id` BIGINT DEFAULT NULL,
  `warehouse_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `tax_percent` DECIMAL(24,6) DEFAULT NULL,
  `tax_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_return_items_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_sale_return_items_parent` (`tenant_id`, `return_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_sale_return_items';

CREATE TABLE `erp_stock_check` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `check_time` DATETIME DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `remark` TEXT,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_check_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_stock_check_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock_check';

CREATE TABLE `erp_stock_check_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `check_id` BIGINT DEFAULT NULL,
  `warehouse_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `stock_count` DECIMAL(24,6) DEFAULT NULL,
  `actual_count` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_check_item_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_stock_check_item_parent` (`tenant_id`, `check_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock_check_item';

CREATE TABLE `erp_stock` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT NOT NULL,
  `warehouse_id` BIGINT NOT NULL,
  `count` DECIMAL(24,6) NOT NULL DEFAULT 0,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_tenant` (`tenant_id`, `deleted`, `id`),
  UNIQUE KEY `uk_erp_stock_tenant_pair` (`tenant_id`, `product_id`, `warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock';

CREATE TABLE `erp_stock_in` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `supplier_id` BIGINT DEFAULT NULL,
  `in_time` DATETIME DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `remark` TEXT,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_in_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_stock_in_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock_in';

CREATE TABLE `erp_stock_in_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `in_id` BIGINT DEFAULT NULL,
  `warehouse_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_in_item_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_stock_in_item_parent` (`tenant_id`, `in_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock_in_item';

CREATE TABLE `erp_stock_move` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `move_time` DATETIME DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `remark` TEXT,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_move_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_stock_move_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock_move';

CREATE TABLE `erp_stock_move_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `move_id` BIGINT DEFAULT NULL,
  `from_warehouse_id` BIGINT DEFAULT NULL,
  `to_warehouse_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_move_item_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_stock_move_item_parent` (`tenant_id`, `move_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock_move_item';

CREATE TABLE `erp_stock_out` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(100) DEFAULT NULL,
  `customer_id` BIGINT DEFAULT NULL,
  `out_time` DATETIME DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `remark` TEXT,
  `file_url` VARCHAR(1024) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_out_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_stock_out_no` (`tenant_id`, `no`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock_out';

CREATE TABLE `erp_stock_out_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `out_id` BIGINT DEFAULT NULL,
  `warehouse_id` BIGINT DEFAULT NULL,
  `product_id` BIGINT DEFAULT NULL,
  `product_unit_id` BIGINT DEFAULT NULL,
  `product_price` DECIMAL(24,6) DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_price` DECIMAL(24,6) DEFAULT NULL,
  `remark` TEXT,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_out_item_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_stock_out_item_parent` (`tenant_id`, `out_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock_out_item';

CREATE TABLE `erp_stock_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT DEFAULT NULL,
  `warehouse_id` BIGINT DEFAULT NULL,
  `count` DECIMAL(24,6) DEFAULT NULL,
  `total_count` DECIMAL(24,6) DEFAULT NULL,
  `biz_type` INT DEFAULT NULL,
  `biz_id` BIGINT DEFAULT NULL,
  `biz_item_id` BIGINT DEFAULT NULL,
  `biz_no` VARCHAR(255) DEFAULT NULL,
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_record_tenant` (`tenant_id`, `deleted`, `id`),
  KEY `idx_erp_stock_record_product` (`tenant_id`, `product_id`, `warehouse_id`, `id`),
  KEY `idx_erp_stock_record_biz` (`tenant_id`, `biz_type`, `biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_stock_record';

CREATE TABLE `erp_warehouse` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `address` VARCHAR(500) DEFAULT NULL,
  `sort` BIGINT DEFAULT NULL,
  `remark` TEXT,
  `principal` VARCHAR(255) DEFAULT NULL,
  `warehouse_price` DECIMAL(24,6) DEFAULT NULL,
  `truckage_price` DECIMAL(24,6) DEFAULT NULL,
  `status` TINYINT DEFAULT NULL,
  `default_status` BIT(1) DEFAULT b'0',
  `creator` VARCHAR(64) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) NOT NULL DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_erp_warehouse_tenant` (`tenant_id`, `deleted`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP erp_warehouse';
